# Generated by Django 5.0.6 on 2024-06-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
    ]
