# Generated by Django 5.0.6 on 2024-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
