# Generated by Django 5.0.6 on 2024-06-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='list_of_jobs',
            field=models.CharField(default='Не определено', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='schedule',
            field=models.CharField(default='Не определено', max_length=200),
        ),
    ]
