# Generated by Django 5.0.6 on 2024-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_alter_employee_list_of_jobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='is_employee',
        ),
    ]
