# Generated by Django 5.0.6 on 2024-06-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['title'], 'verbose_name_plural': 'Article'},
        ),
    ]
